---
repos:
  - repo: https://github.com/RyoWakabayashi/pre-commit-hooks
    rev: v2.5.5
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
      - id: markdownlint
        files: \.(markdown|md)$
